### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sidey79** [Celedhrim/scantopl#6]
I've started the container and pointed it to the output dirctory, but it crashes:

```
2024-11-17T21:33:55.203838889Z time="2024-11-17T21:33:55Z" level=info msg="Start watching: /output"
2024-11-17T21:35:12.703855921Z time="2024-11-17T21:35:12Z" level=info msg="New file to upload:/output/pl_scan_2024-11-17 21.35.04.pdf"
2024-11-17T21:35:12.711801367Z panic: runtime error: invalid memory address or nil pointer dereference
2024-11-17T21:35:12.711863858Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x62fc2f]
2024-11-17T21:35:12.711886032Z 
2024-11-17T21:35:12.711905848Z goroutine 7 [running]:
2024-11-17T21:35:12.711929241Z main.uploadFile({0xc000120150, 0x27}, {0xc00001c036, 0x28}, {0xc00001c008, 0x28})
2024-11-17T21:35:12.711974592Z 	/go/src/github.com/Celedhrim/scantopl/scantopl.go:62 +0x26f
2024-11-17T21:35:12.712275125Z main.main.func1()
2024-11-17T21:35:12.712310093Z 	/go/src/github.com/Celedhrim/scantopl/scantopl.go:119 +0x27d
2024-11-17T21:35:12.712331177Z created by main.main
2024-11-17T21:35:12.712349777Z 	/go/src/github.com/Celedhrim/scantopl/scantopl.go:107 +0x38
```

**Comment by sidey79** [comment]
Any idea, what i can do to fix that?

**Comment by sidey79** [comment]
I fixed it myself using a updated fork, which i also updated a little bit and now my files get uploaded to paperless without any errors

https://github.com/sidey79/scantopl
